apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: cluster-dev
    profiles: []
  - targetId: cluster-prod
    profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cluster-dev
description: development cluster
gke:
  cluster: projects/my-demo-project-442910/locations/us-central1-c/clusters/cluster-dev
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cluster-prod
description: production cluster
gke:
  cluster: projects/my-demo-project-442910/locations/us-central1-c/clusters/cluster-prod
