steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-demo-project-442910/nodejs-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/my-demo-project-442910/nodejs-app:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'deploy'
  - 'releases'
  - 'create'
  - 'nodejs-release-$SHORT_SHA'
  - '--delivery-pipeline=my-gke-demo-app-1'
  - '--region=us-central1'
  - '--images=nodejs-app=gcr.io/my-demo-project-442910/nodejs-app:latest'
options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'gcr.io/my-demo-project-442910/nodejs-app:latest'
